# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
#  export ZSH="/home/ondrej/.oh-my-zsh"
#
setopt promptsubst
source /usr/share/zsh/share/antigen.zsh
antigen use prezto
antigen bundle sorin-ionescu/prezto modules/helper  # required for Git module
antigen bundle sorin-ionescu/prezto modules/editor
antigen bundle sorin-ionescu/prezto modules/git
antigen bundle sorin-ionescu/prezto modules/prompt
antigen bundle sorin-ionescu/prezto modules/history
antigen bundle zdharma/fast-syntax-highlighting 
antigen bundle sorin-ionescu/prezto modules/completion
antigen bundle sorin-ionescu/prezto modules/directory
antigen bundle sorin-ionescu/prezto modules/terminal
antigen bundle hlissner/zsh-autopair
antigen bundle zdharma/history-search-multi-word

#antigen theme skwp

antigen apply
setopt clobber

alias cp='cp -r --reflink=auto'
alias df='pydf'
alias diff='kitty +kitten diff'
alias dragall='dragon-drag-and-drop --and-exit --all'
alias dragon='dragon-drag-and-drop --and-exit'
alias e='kak'
alias grep='grep --color'
alias http-serve='python3 -m http.server'
alias locate='locate -i'
alias mkdir='mkdir -p'
alias o='xdg-open'
alias rg='rg --hidden --follow --smart-case 2>/dev/null'
alias rm!='\rm -rf'
alias rsync='rsync --verbose --archive --info=progress2 --human-readable --compress --partial'
alias sudo='sudo -E '

alias ls="exa --git --group-directories-first"
alias ll="ls -l"
alias la="ll -a"
alias lk="ll -s=size"                # Sorted by size
alias lm="ll -s=modified"            # Sorted by modified date
alias lc="ll --created -s=created"   # Sorted by created date
alias l="ll"

alias pjv='cd ~/School/BI-PJV/FirstEffort'
alias pizza='cd ~/Work/imatic/pizza360'

h=()
if [[ -r ~/.ssh/config ]]; then
  h=($h ${${${(@M)${(f)"$(cat ~/.ssh/config)"}:#Host *}#Host }:#*[*?]*})
fi
if [[ -r ~/.ssh/known_hosts ]]; then
  h=($h ${${${(f)"$(cat ~/.ssh/known_hosts{,2} || true)"}%%\ *}%%,*}) 2>/dev/null
fi
if [[ $#h -gt 0 ]]; then
  zstyle ':completion:*:ssh:*' hosts $h
  zstyle ':completion:*:slogin:*' hosts $h
fi

### Coloring man pages ###
man() {
    LESS_TERMCAP_md=$'\e[01;31m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_se=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[01;44;33m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[01;32m' \
    command man "$@"
}

#source /usr/share/nvm/init-nvm.sh

#adding phpfarm to path
PATH="$HOME/phpfarm/inst/bin:$HOME/phpfarm/inst/current/bin:$HOME/phpfarm/inst/current/sbin:$PATH"

#ssh-agent starting
#if ! pgrep -u "$USER" ssh-agent > /dev/null; then
#    ssh-agent > ~/.ssh-agent-thing
#fi
#if [[ "$SSH_AGENT_PID" == "" ]]; then
#    eval "$(<~/.ssh-agent-thing)"
#fi

#export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

#exporting path with every command
export PROMPT_COMMAND="pwd > /tmp/whereami"
precmd() { eval "$PROMPT_COMMAND" }
alias whereami='cat /tmp/whereami'

PATH="$HOME/.node_modules/bin:$PATH"
export npm_config_prefix=~/.node_modules

autoload -Uz promptinit
promptinit
prompt skwp 

alias clip='xsel --clipboard'
alias dotdrop=~/.dotfiles/dotdrop.sh --cfg=~/.dotfiles/config.yaml'

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(time)
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="red"
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="cornsilk1"
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="grey27"
